### ISSUE TITLE
"true" not accepted as boolean value

### ISSUE THREAD

**Issue by spslinger** [igniterealtime/openfire-search-plugin#3]
Since Smack version 4.2.?, the positive value for boolean fields in forms is sent as "true" instead of "1". The Search plugin only accepts "1", and therefore the Search plugin cannot be used in combination with the latest Smack libraries.

Both "1" and "true" should be accepted according to XEP-0004, Appendix G: Notes:
10. In accordance with Section 3.2.2.1 of XML Schema Part 2: Datatypes, the allowable lexical representations for the xs:boolean datatype are the strings "0" and "false" for the concept 'false' and the strings "1" and "true" for the concept 'true'; implementations MUST support both styles of lexical representation.

**Comment by guusdk** [comment]
Although you're likely right, I cannot immediately determine how the search plugin would process a search field that is not any of the standard fields (which are text-based). How do you reproduce this problem?

**Comment by GregDThomas** [comment]
I've no idea what the packets should look like, but to me it seems that https://github.com/igniterealtime/openfire-search-plugin/blob/master/src/java/org/jivesoftware/openfire/plugin/SearchPlugin.java#L705 is probably the culprit.

**Comment by hartprince** [comment]
> I've no idea what the packets should look like, but to me it seems that https://github.com/igniterealtime/openfire-search-plugin/blob/master/src/java/org/jivesoftware/openfire/plugin/SearchPlugin.java#L705 is probably the culprit.
 
Yes, that's the problem. Change the if condition to value.equals("1") || value.equals("true") will fix the problem.

**Comment by spslinger** [comment]
Yes, I concur. Line 705 only checks for "1" and should allow "true" as well. Give the case-impaired a break and use equalsIgnoreCase.

Example of packet being sent by client:
<iq to='search.myserver' id='02iaD-747' type='set'><query xmlns='jabber:iq:search'><x xmlns='jabber:x:data' type='submit'><field var='FORM_TYPE' type='hidden'><value>jabber:iq:search</value></field><field var='search' type='text-single'><value>Guus</value></field><field var='Username' type='boolean'><value>true</value></field><field var='Name' type='boolean'><value>true</value></field><field var='Email' type='boolean'><value>true</value></field></x></query></iq>

**Comment by vkelman** [comment]
Hello,

Is extended search convention / logic implemented by Openfire Search plugin in extractExtendedSearchQuery() method a common approach?  Do XMPP chat client libraries usually submit extended search queries in that format?

I'm asking about this:

If extended search is requested by client by submitting `<x xmlns='jabber:x:data'>`  XML clause, do the following:

1. Look for <field var='search'><value>_a_search_term_</value></field>
2. Look for search fields with values equal to to "1" or "true", replace those with _a_search_term_ 
3. Use resulting filled-out fields to actually search in [for-loop](https://github.com/igniterealtime/openfire-search-plugin/blob/master/src/java/org/jivesoftware/openfire/plugin/SearchPlugin.java#L602) (by calling userManager.findUsers() - implementing "OR" logic on search (Username = _a_search_term_ OR Name = _a_search_term_ OR Email = _a_search_term_).
